// Typed architecture exceptions: docs/spec/agent-infrastructure.md, Exceptions. Only the workspace scope
// reads this file. Each entry names one exact site, its expected count and the owning decision that
// authorizes it; a reusable allowance belongs in the tested policy instead. A ULT-DOCS-001 entry pins
// the declared expression and its condition, so a changed value in an excepted declaration is a new site.
import type { ArchitectureException } from './src/exceptions.ts';

export default [
  {
    id: 'drawer-backdrop-swiping-cancels-transition',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/drawer.tsx',
    symbol: 'styles.backdrop',
    target: 'transitionDuration',
    selector: ':is([data-swiping])',
    expression: "'0s'",
    count: 1,
    reason: 'While the panel follows a finger the backdrop has no transition at all, rather than a fast one.',
    authority: 'docs/spec/ultima.md#motion',
  },
  {
    id: 'navigation-menu-positioner-instant-cancels-transition',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/navigation-menu.tsx',
    symbol: 'styles.positioner',
    target: 'transitionDuration',
    selector: ':is([data-instant])',
    expression: "'0s'",
    count: 1,
    reason: 'The positioner cancels its transition through the longhand under [data-instant].',
    authority: 'docs/spec/ultima.md#state-styling',
  },
  {
    id: 'toast-intra-stack-z-index',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/toast.tsx',
    symbol: 'styles.root',
    target: 'zIndex',
    expression: '`calc(${stackCeiling} - var(--toast-index))`',
    count: 1,
    reason: 'The z-index arithmetic among toast roots is a module constant in toast.tsx, not a token.',
    authority: 'docs/spec/ultima.md#border-widths-and-z-index',
  },
  {
    id: 'avatar-fallback-initials-track-the-box',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/avatar.tsx',
    symbol: 'styles.fallback',
    target: 'fontSize',
    expression: "'40cqi'",
    count: 1,
    reason: "The initials track the box through the system's first container query, not a text step.",
    authority: 'docs/spec/ultima.md#the-toggle-accordion-avatar-and-scroll-area-set',
  },
  {
    id: 'native-select-chevron-room',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/native-select.tsx',
    symbol: 'styles.select',
    target: 'paddingInlineEnd',
    expression: 'chevronRoom',
    count: 1,
    reason: 'The inline-end padding leaves the 1em chevron glyph its room between two space steps.',
    authority: 'docs/spec/ultima.md#per-component-notes',
  },
  {
    id: 'color-field-hue-track',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'styles.hue',
    target: 'backgroundImage',
    count: 1,
    reason: "The hue slider's track depicts the hue circle itself, which no semantic token can.",
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'color-field-saturation-brightness-area',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'paints.area',
    target: 'backgroundImage',
    count: 1,
    reason: 'The picker area depicts saturation and brightness at the current hue: black, white and the pure hue.',
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'color-field-swatch-paints-the-value',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'paints.fill',
    target: 'backgroundColor',
    expression: 'backgroundColor',
    count: 1,
    reason: "ColorField.Swatch paints the field's current value, a runtime color the consumer chose.",
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'theme-studio-preview-applies-the-draft',
    rule: 'ULT-STYLE-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'PreviewPane',
    target: 'style',
    count: 1,
    reason: "The preview boundary applies the draft's resolved --ult-* table inline, the theme application the resolver feeds.",
    authority: 'docs/spec/theme-studio.md#theme-export-installation-and-recovery',
  },
  {
    id: 'copy-button-icon-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/copy-button.tsx',
    symbol: 'styles.icon',
    target: 'backgroundColor',
    expression: "color['--ult-color-surface-sunken']",
    count: 1,
    reason: 'The copy icon button takes a surface-sunken backdrop over scrolling code below the wide breakpoint, and restates the ghost hover over it, settled on #369.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'copy-button-icon-background-color-hover',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/copy-button.tsx',
    symbol: 'styles.icon',
    target: 'backgroundColor',
    selector: ':hover',
    expression: "color['--ult-color-surface-hover']",
    count: 1,
    reason: 'The copy icon button takes a surface-sunken backdrop over scrolling code below the wide breakpoint, and restates the ghost hover over it, settled on #369.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'copy-button-icon-background-color-media-min-width-48rem-hover',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/copy-button.tsx',
    symbol: 'styles.icon',
    target: 'backgroundColor',
    selector: '@media (min-width: 48rem) :hover',
    expression: "color['--ult-color-surface-hover']",
    count: 1,
    reason: 'The copy icon button takes a surface-sunken backdrop over scrolling code below the wide breakpoint, and restates the ghost hover over it, settled on #369.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'header-chrome-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/header.tsx',
    symbol: 'styles.chrome',
    target: 'backgroundColor',
    expression: "color['--ult-color-surface']",
    count: 1,
    reason: 'The sticky header restates the page ground so scrolled content stays hidden under it, settled on #337.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'studio-shell-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/routes/theme-studio.tsx',
    symbol: 'styles.shell',
    target: 'backgroundColor',
    expression: "color['--ult-color-surface']",
    count: 1,
    reason: 'Studio chrome paints its own surfaces without introducing a component.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-editor-border-inline-end-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/routes/theme-studio.tsx',
    symbol: 'styles.editor',
    target: 'borderInlineEndColor',
    expression: "color['--ult-color-border']",
    count: 1,
    reason: 'Studio chrome paints its own surfaces without introducing a component.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-editor-border-inline-end-width-media-min-width-52-5rem',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/routes/theme-studio.tsx',
    symbol: 'styles.editor',
    target: 'borderInlineEndWidth',
    selector: '@media (min-width: 52.5rem)',
    expression: 'border.hairline',
    count: 1,
    reason: 'Studio chrome paints its own surfaces without introducing a component.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-status-border-block-start-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/routes/theme-studio.tsx',
    symbol: 'styles.status',
    target: 'borderBlockStartColor',
    expression: "color['--ult-color-border']",
    count: 1,
    reason: 'Studio chrome paints its own surfaces without introducing a component.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-status-border-block-start-width',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/routes/theme-studio.tsx',
    symbol: 'styles.status',
    target: 'borderBlockStartWidth',
    expression: 'border.hairline',
    count: 1,
    reason: 'Studio chrome paints its own surfaces without introducing a component.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'swatch-chip-border-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/swatch.tsx',
    symbol: 'styles.chip',
    target: 'borderColor',
    expression: "color['--ult-color-border']",
    count: 1,
    reason: 'Swatch displays a raw palette value; its chip is the stated exception.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'swatch-chip-border-radius',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/swatch.tsx',
    symbol: 'styles.chip',
    target: 'borderRadius',
    expression: "radius['--ult-radius-xs']",
    count: 1,
    reason: 'Swatch displays a raw palette value; its chip is the stated exception.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'swatch-chip-border-width',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/swatch.tsx',
    symbol: 'styles.chip',
    target: 'borderWidth',
    expression: 'border.hairline',
    count: 1,
    reason: 'Swatch displays a raw palette value; its chip is the stated exception.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'swatch-chip-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/swatch.tsx',
    symbol: 'fill.chip',
    target: 'backgroundColor',
    expression: 'value',
    count: 1,
    reason: 'Swatch displays a raw palette value; its chip is the stated exception.',
    authority: 'docs/spec/ultima.md#painted-declarations-the-docs-keeps',
  },
  {
    id: 'studio-preview-canvas-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.canvas',
    target: 'backgroundColor',
    expression: "color['--ult-color-surface']",
    count: 1,
    reason: 'The preview canvas frames each pane in the draft theme, settled on #374.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-canvas-border-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.canvas',
    target: 'borderColor',
    expression: "color['--ult-color-border']",
    count: 1,
    reason: 'The preview canvas frames each pane in the draft theme, settled on #374.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-canvas-border-radius',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.canvas',
    target: 'borderRadius',
    expression: "radius['--ult-radius-lg']",
    count: 1,
    reason: 'The preview canvas frames each pane in the draft theme, settled on #374.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-canvas-border-width',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.canvas',
    target: 'borderWidth',
    expression: 'border.hairline',
    count: 1,
    reason: 'The preview canvas frames each pane in the draft theme, settled on #374.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-stat-border-block-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.stat',
    target: 'borderBlockColor',
    expression: "color['--ult-color-border']",
    count: 1,
    reason: "The Workspace scene's stat rows are an application mock drawn in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-stat-border-block-width',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.stat',
    target: 'borderBlockWidth',
    expression: 'border.hairline',
    count: 1,
    reason: "The Workspace scene's stat rows are an application mock drawn in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-project-icon-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.projectIcon',
    target: 'backgroundColor',
    expression: "color['--ult-color-accent-subtle']",
    count: 1,
    reason: "The Workspace scene's project glyph is an application mock drawn in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-project-icon-border-radius',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.projectIcon',
    target: 'borderRadius',
    expression: "radius['--ult-radius-sm']",
    count: 1,
    reason: "The Workspace scene's project glyph is an application mock drawn in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-invite-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.invite',
    target: 'backgroundColor',
    expression: "color['--ult-color-accent-subtle']",
    count: 1,
    reason: "The Workspace scene's invite card restates Card at the accent tone, as an application mock in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-invite-border-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.invite',
    target: 'borderColor',
    expression: "color['--ult-color-accent-border']",
    count: 1,
    reason: "The Workspace scene's invite card restates Card at the accent tone, as an application mock in the draft theme.",
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-raised-box-shadow',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.raised',
    target: 'boxShadow',
    expression: "shadow['--ult-shadow-md']",
    count: 1,
    reason: 'The Surfaces scene shows the raised shadow on a Card.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-hover-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.hover',
    target: 'backgroundColor',
    expression: "color['--ult-color-accent-hover']",
    count: 1,
    reason: 'The States scene renders the hover variant at rest.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-preview-active-background-color',
    rule: 'ULT-DOCS-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'styles.active',
    target: 'backgroundColor',
    expression: "color['--ult-color-accent-active']",
    count: 1,
    reason: 'The States scene renders the active variant at rest.',
    authority: 'docs/spec/theme-studio.md#theme-studio-layout-and-live-preview',
  },
  {
    id: 'studio-actions-file-input',
    rule: 'ULT-DOCS-002',
    path: 'apps/docs/src/theme-studio-actions.tsx',
    symbol: 'StudioActions',
    target: '<input>',
    count: 1,
    reason: 'The hidden file chooser the Open Button clicks; it is never shown or focused, and the Button is the control.',
    authority: 'docs/spec/theme-studio.md#theme-export-installation-and-recovery',
  },
] satisfies ArchitectureException[];
