// Typed architecture exceptions: docs/spec/agent-infrastructure.md, Exceptions. Only the workspace scope
// reads this file. Each entry names one exact site, its expected count and the owning decision that
// authorizes it; a reusable allowance belongs in the tested policy instead.
import type { ArchitectureException } from './src/exceptions.ts';

export default [
  {
    id: 'drawer-backdrop-swiping-cancels-transition',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/drawer.tsx',
    symbol: 'styles.backdrop',
    target: 'transitionDuration',
    selector: ':is([data-swiping])',
    expression: "'0s'",
    count: 1,
    reason: 'While the panel follows a finger the backdrop has no transition at all, rather than a fast one.',
    authority: 'docs/spec/ultima.md#motion',
  },
  {
    id: 'navigation-menu-positioner-instant-cancels-transition',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/navigation-menu.tsx',
    symbol: 'styles.positioner',
    target: 'transitionDuration',
    selector: ':is([data-instant])',
    expression: "'0s'",
    count: 1,
    reason: 'The positioner cancels its transition through the longhand under [data-instant].',
    authority: 'docs/spec/ultima.md#state-styling',
  },
  {
    id: 'toast-intra-stack-z-index',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/toast.tsx',
    symbol: 'styles.root',
    target: 'zIndex',
    expression: '`calc(${stackCeiling} - var(--toast-index))`',
    count: 1,
    reason: 'The z-index arithmetic among toast roots is a module constant in toast.tsx, not a token.',
    authority: 'docs/spec/ultima.md#border-widths-and-z-index',
  },
  {
    id: 'avatar-fallback-initials-track-the-box',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/avatar.tsx',
    symbol: 'styles.fallback',
    target: 'fontSize',
    expression: "'40cqi'",
    count: 1,
    reason: "The initials track the box through the system's first container query, not a text step.",
    authority: 'docs/spec/ultima.md#the-toggle-accordion-avatar-and-scroll-area-set',
  },
  {
    id: 'native-select-chevron-room',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/native-select.tsx',
    symbol: 'styles.select',
    target: 'paddingInlineEnd',
    expression: 'chevronRoom',
    count: 1,
    reason: 'The inline-end padding leaves the 1em chevron glyph its room between two space steps.',
    authority: 'docs/spec/ultima.md#per-component-notes',
  },
  {
    id: 'color-field-hue-track',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'styles.hue',
    target: 'backgroundImage',
    count: 1,
    reason: "The hue slider's track depicts the hue circle itself, which no semantic token can.",
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'color-field-saturation-brightness-area',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'paints.area',
    target: 'backgroundImage',
    count: 1,
    reason: 'The picker area depicts saturation and brightness at the current hue: black, white and the pure hue.',
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'color-field-swatch-paints-the-value',
    rule: 'ULT-TOKEN-001',
    path: 'packages/ui/src/color-field.tsx',
    symbol: 'paints.fill',
    target: 'backgroundColor',
    expression: 'backgroundColor',
    count: 1,
    reason: "ColorField.Swatch paints the field's current value, a runtime color the consumer chose.",
    authority: 'docs/spec/theme-studio.md#studio-support-components-and-compositions',
  },
  {
    id: 'theme-studio-preview-applies-the-draft',
    rule: 'ULT-STYLE-001',
    path: 'apps/docs/src/theme-studio-preview.tsx',
    symbol: 'PreviewPane',
    target: 'style',
    count: 1,
    reason: "The preview boundary applies the draft's resolved --ult-* table inline, the theme application the resolver feeds.",
    authority: 'docs/spec/theme-studio.md#theme-export-installation-and-recovery',
  },
] satisfies ArchitectureException[];
