import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, test } from 'node:test';

import type { OptimizerPolicy } from './browser.ts';
import { memoryFiles } from './files.ts';
import { diskFixture as fixture, testPolicy as policy, validFixture } from './fixture.ts';
import { GenerationError, LOCK, check, generate } from './generate.ts';
import { formatDiagnostics } from './model.ts';
import { OUTPUTS, anatomyModule, planOutputs } from './projections.ts';

const roots: string[] = [];
after(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

function onDisk(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), 'ultima-catalogue-'));
  roots.push(root);
  for (const [path, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), text);
  }
  return root;
}

function snapshot(root: string, directory = ''): Record<string, string> {
  const found: Record<string, string> = {};
  for (const name of readdirSync(join(root, directory))) {
    const path = directory ? `${directory}/${name}` : name;
    if (statSync(join(root, path)).isDirectory()) Object.assign(found, snapshot(root, path));
    else found[path] = readFileSync(join(root, path), 'utf8');
  }
  return found;
}

const read = (root: string, path: string) => readFileSync(join(root, path), 'utf8');

const body = (text: string) => text.split('\n').slice(3).join('\n');

describe('the planned projections', () => {
  const { outputs, optimizer, diagnostics } = planOutputs(memoryFiles(fixture()), policy);

  test('plan without a diagnostic', () => assert.deepEqual(diagnostics, []));

  test('own exactly the fixed outputs and one anatomy module per React item, each under its header', () => {
    const anatomy = ['button', 'calendar', 'input-otp', 'sidebar'].map(anatomyModule);
    assert.deepEqual([...outputs.keys()].sort(), [...Object.values(OUTPUTS), ...anatomy].sort());
    for (const text of outputs.values()) assert.match(text, /^\/\/ Generated by `pnpm catalogue:generate` from /);
  });

  test('mark every part that renders an element, and re-export the rest of the item unchanged', () => {
    assert.equal(
      body(outputs.get(anatomyModule('button')) as string),
      [
        "import { Button as Source } from '@ultima/ui/button';",
        '',
        "import { mark } from '../../anatomy-mark';",
        '',
        'export {',
        '  type ButtonProps,',
        "} from '@ultima/ui/button';",
        '',
        "export const Button = mark(Source, 'button', 'Button');",
        '',
      ].join('\n'),
    );
    assert.match(
      outputs.get(anatomyModule('sidebar')) as string,
      /export \{\n  type SidebarRootProps,\n  useSidebar,\n\} from '@ultima\/ui\/sidebar';\n\nexport const Sidebar = \{\n  \.\.\.Source,\n  Root: mark\(Source\.Root, 'sidebar', 'Root'\),\n\};\n$/,
    );
    assert.match(outputs.get(OUTPUTS.anatomyBarrel) as string, /export \{\n  type SidebarRootProps,\n  Sidebar,\n  useSidebar,\n\} from '\.\/sidebar';/);
    assert.match(outputs.get(OUTPUTS.anatomy) as string, /'button': \{ parts: \['Button'\] \},\n  'calendar': \{ parts: \['Root'\] \},/);
  });

  test('leave an elementless part unwrapped, and reject one the item does not export', () => {
    const files = fixture();
    const path = 'registry/metadata/react/sidebar.ts';
    files[path] = (files[path] as string).replace("group: 'navigation'", "group: 'navigation',\n  elementless: ['Root']").replace('"group": "navigation"', '"group": "navigation",\n  "elementless": ["Root"]');
    const planned = planOutputs(memoryFiles(files), policy);
    assert.deepEqual(planned.diagnostics, []);
    assert.match(planned.outputs.get(anatomyModule('sidebar')) as string, /export const Sidebar = \{\n  \.\.\.Source,\n\};/);
    files[path] = (files[path] as string).replace('["Root"]', '["Popup"]');
    assert.match(formatDiagnostics(planOutputs(memoryFiles(files), policy).diagnostics), /elementless names "Popup", which is not a part of Sidebar/);
  });

  test('re-export each component file explicitly, aliases resolved and type modifiers kept', () => {
    assert.equal(
      body(outputs.get(OUTPUTS.barrel) as string),
      [
        'export {',
        '  Button,',
        '  type ButtonProps,',
        "} from './button';",
        'export {',
        '  Calendar,',
        "} from './calendar';",
        'export {',
        '  InputOTP,',
        '  type InputOTPSize,',
        "} from './input-otp';",
        'export {',
        '  type SidebarRootProps,',
        '  Sidebar,',
        '  useSidebar,',
        "} from './sidebar';",
        '',
      ].join('\n'),
    );
  });

  test('import every registered page eagerly, named for its primary export', () => {
    const pages = outputs.get(OUTPUTS.pages) as string;
    assert.match(pages, /^import InputOTPContent from '\.\.\/content\/components\/input-otp\.mdx';$/m);
    assert.match(pages, /^ {2}"input-otp": InputOTPContent,$/m);
    assert.equal(pages.match(/^import \w+Content from/gm)?.length, 4);
  });

  test('order the docs catalogue by group, then alphabetically, with numbers and the visitor prose', () => {
    const text = outputs.get(OUTPUTS.catalogue) as string;
    assert.match(text, /export const GROUPS = \[\n {2}\{\n {4}"id": "forms",\n {4}"label": "Forms"\n {2}\},\n {2}\{\n {4}"id": "navigation",\n {4}"label": "Navigation"\n {2}\}\n\] as const;/);
    assert.match(text, /export const RELEASES = \[\n {2}"v0",\n {2}"v0\.1"\n\] as const;/);
    assert.doesNotMatch(text, /RELEASE_LABELS/);
    assert.deepEqual(
      [...text.matchAll(/"item": "([\w-]+)",\n {4}"number": "(\d+)",\n {4}"group": "([\w-]+)"/g)].map((match) => match.slice(1)),
      [
        ['button', '001', 'forms'],
        ['calendar', '002', 'forms'],
        ['input-otp', '003', 'forms'],
        ['sidebar', '004', 'navigation'],
      ],
    );
  });

  test('name the primitive each component builds on from its imports', () => {
    const text = outputs.get(OUTPUTS.catalogue) as string;
    const primitives = Object.fromEntries(
      [...text.matchAll(/"item": "([\w-]+)",[\s\S]*?"primitive": (null|\{[^}]*\})/g)].map(([, item, primitive]) => [item, JSON.parse(primitive as string)]),
    );
    assert.deepEqual(primitives, {
      button: { library: 'base-ui', module: 'button' },
      calendar: { library: 'zag', module: 'date-picker' },
      'input-otp': { library: 'base-ui', module: 'otp-field' },
      sidebar: null,
    });
  });

  test('read element values from the source table and keep the joined attribute presentation', () => {
    const text = outputs.get(OUTPUTS.elements) as string;
    assert.match(text, /"values": \[\n\s+"solid",\n\s+"outline"\n\s+\]/);
    assert.match(text, /"name": "aria-label, aria-labelledby"/);
  });

  test('keep recipes out of the registry projection and serialize element edges as URLs', () => {
    const text = outputs.get(OUTPUTS.registry) as string;
    assert.doesNotMatch(text, /"data-table"/);
    assert.match(text, /"https:\/\/ultima\.systems\/r\/tokens-css\.json"/);
    assert.match(text, /"setup-vite": \{/);
  });

  test('derive separate optimizer sets from each project’s runtime import closure', () => {
    assert.deepEqual(optimizer.include.ui, [
      '@base-ui/react/button',
      '@stylexjs/stylex',
      '@zag-js/date-picker',
      '@zag-js/react',
      'vitest-browser-react',
    ]);
    assert.deepEqual(optimizer.include.docs, [
      '@base-ui/react/button',
      '@stylexjs/stylex',
      '@tanstack/react-table',
      'd3-format',
      'react-dom/client',
    ]);
    assert.equal(optimizer.provenance.docs.get('d3-format'), 'apps/docs/src/demos/button/rows.ts:1');
  });

  test('reject a candidate its importing package does not declare', () => {
    const files = fixture();
    files['apps/docs/package.json'] = JSON.stringify({ name: '@ultima/docs', dependencies: { '@tanstack/react-table': '1', 'react-dom': '1' } });
    const found = planOutputs(memoryFiles(files), policy).diagnostics;
    assert.deepEqual(
      found.map((d) => [d.code, d.path]),
      [['unresolved-dependency', 'apps/docs/src/demos/button/rows.ts:1']],
    );
  });

  test('reject a policy entry discovery already covers or no longer needs', () => {
    const stale: OptimizerPolicy = {
      ui: { add: [{ specifier: '@zag-js/react', reason: 'r', source: 's' }], exclude: policy.ui.exclude },
      docs: { add: policy.docs.add, exclude: [...policy.docs.exclude, { specifier: 'lodash', reason: 'r', source: 's' }] },
      blocks: policy.blocks,
    };
    const found = planOutputs(memoryFiles(fixture()), stale).diagnostics;
    assert.deepEqual(found.map((d) => d.code), ['stale-policy', 'stale-policy']);
  });

  test('plan the same bytes whether the committed projections are absent, stale or current', () => {
    const stale = { ...fixture(), [OUTPUTS.barrel]: "export { Retired } from './retired';\n", [OUTPUTS.pages]: 'export {};\n' };
    const current = { ...fixture(), ...Object.fromEntries(outputs) };
    assert.deepEqual(planOutputs(memoryFiles(stale), policy).outputs, outputs);
    assert.deepEqual(planOutputs(memoryFiles(current), policy).outputs, outputs);
  });
});

describe('generation on disk', () => {
  test('writes every projection with all of them absent, then repeats with zero diff', () => {
    const root = onDisk(fixture());
    const planned = [...planOutputs(memoryFiles(fixture()), policy).outputs.keys()];
    assert.deepEqual(generate(root, { policy }).written, planned);
    assert.deepEqual(check(root, policy), { diagnostics: [], freshness: { added: [], changed: [], stale: [] }, paths: [...planned].sort() });
    const before = snapshot(root);
    assert.deepEqual(generate(root, { policy }).written, []);
    assert.deepEqual(snapshot(root), before);
  });

  test('rejects invalid inputs before writing anything', () => {
    const files = fixture();
    files['registry/metadata/react/sidebar.ts'] = (files['registry/metadata/react/sidebar.ts'] as string).replace('"order": 2', '"order": 1');
    const root = onDisk(files);
    assert.throws(() => generate(root, { policy }), (error: GenerationError) => /duplicate-order/.test(error.message));
    for (const path of Object.values(OUTPUTS)) assert.equal(existsSync(join(root, path)), false, path);
  });

  test('refuses to replace an authored file at an owned path until it is adopted', () => {
    const root = onDisk(preMigrationFixture());
    const authored = [read(root, OUTPUTS.registry), read(root, OUTPUTS.barrel)];
    assert.throws(() => generate(root, { policy }), /registry\/items\.config\.ts holds an authored file/);
    assert.throws(() => generate(root, { policy, adopt: [OUTPUTS.registry] }), /packages\/ui\/src\/index\.ts holds an authored file/);
    assert.deepEqual([read(root, OUTPUTS.registry), read(root, OUTPUTS.barrel)], authored);
    assert.equal(existsSync(join(root, OUTPUTS.catalogue)), false);
    generate(root, { policy, adopt: [OUTPUTS.barrel, OUTPUTS.registry] });
    assert.equal(check(root, policy).freshness.changed.length, 0);
  });

  test('check reports added, changed and stale paths without repairing them', () => {
    const root = onDisk(fixture());
    generate(root, { policy });
    writeFileSync(join(root, OUTPUTS.catalogue), `${read(root, OUTPUTS.catalogue)}// hand edit\n`);
    rmSync(join(root, OUTPUTS.elements));
    writeFileSync(join(root, 'apps/docs/src/generated/retired.ts'), 'export {};\n');
    const before = snapshot(root);
    assert.deepEqual(check(root, policy).freshness, {
      added: [OUTPUTS.elements],
      changed: [OUTPUTS.catalogue],
      stale: ['apps/docs/src/generated/retired.ts'],
    });
    assert.deepEqual(snapshot(root), before);
  });

  test('aborts without writing when an input changes during generation', () => {
    const root = onDisk(fixture());
    const edit = () => writeFileSync(join(root, 'packages/ui/src/calendar.tsx'), `${read(root, 'packages/ui/src/calendar.tsx')}\n`);
    assert.throws(() => generate(root, { policy, beforeWrite: edit }), /changed while generating[^]*packages\/ui\/src\/calendar\.tsx/);
    for (const path of Object.values(OUTPUTS)) assert.equal(existsSync(join(root, path)), false, path);
    assert.equal(existsSync(join(root, LOCK)), false);
  });

  test('aborts without writing when a new input appears during generation', () => {
    const root = onDisk(fixture());
    const add = () => writeFileSync(join(root, 'registry/metadata/react/extra.ts'), 'export default {};\n');
    assert.throws(() => generate(root, { policy, beforeWrite: add }), /changed while generating[^]*registry\/metadata\/react\//);
    assert.equal(existsSync(join(root, OUTPUTS.barrel)), false);
  });

  test('refuses while another generation holds this worktree’s lock', () => {
    const root = onDisk(fixture());
    writeFileSync(join(root, LOCK), '1\n');
    assert.throws(() => generate(root, { policy }), /another generation is running/);
    assert.equal(existsSync(join(root, OUTPUTS.barrel)), false);
    assert.equal(existsSync(join(root, LOCK)), true);
  });

  test('reports every path written before a failed write, and check keeps failing', () => {
    const root = onDisk(fixture());
    mkdirSync(join(root, OUTPUTS.elements), { recursive: true });
    assert.throws(
      () => generate(root, { policy }),
      (error: GenerationError) => {
        assert.deepEqual(error.written, [OUTPUTS.registry, OUTPUTS.catalogue, OUTPUTS.pages]);
        assert.match(
          error.message,
          /not written: apps\/docs\/src\/generated\/elements\.ts, apps\/docs\/src\/generated\/blocks\.ts, apps\/docs\/src\/generated\/anatomy-tabs\.ts, .*, packages\/ui\/src\/index\.ts, scripts\/generated\/browser-dependencies\.ts/,
        );
        return true;
      },
    );
    const anatomy = ['button', 'calendar', 'input-otp', 'sidebar'].map(anatomyModule);
    assert.deepEqual(check(root, policy).freshness.added, [
      OUTPUTS.elements,
      OUTPUTS.blocks,
      OUTPUTS.anatomy,
      OUTPUTS.anatomyBarrel,
      ...anatomy,
      OUTPUTS.barrel,
      OUTPUTS.browser,
    ]);
    assert.equal(existsSync(join(root, LOCK)), false);
  });
});

function preMigrationFixture(): Record<string, string> {
  const { [OUTPUTS.barrel]: barrel, [OUTPUTS.registry]: registry } = validFixture();
  return { ...fixture(), [OUTPUTS.barrel]: barrel as string, [OUTPUTS.registry]: registry as string };
}
