import { type OptimizerPlan, type OptimizerPolicy, browserDependencies, ordinal } from './browser.ts';
import type { Files } from './files.ts';
import { BARREL, type Catalogue, type Diagnostic, loadCatalogue } from './model.ts';

/** Every path the generator owns. It writes these and nothing else. */
export const OUTPUTS = {
  registry: 'registry/items.config.ts',
  catalogue: 'apps/docs/src/generated/catalogue.ts',
  pages: 'apps/docs/src/generated/component-pages.ts',
  elements: 'apps/docs/src/generated/elements.ts',
  barrel: BARREL,
  browser: 'scripts/generated/browser-dependencies.ts',
} as const;

/** Directories holding only generated files, so anything else there is stale. */
export const GENERATED_DIRECTORIES = ['apps/docs/src/generated', 'scripts/generated'];

export const HEADER_MARK = 'Generated by `pnpm catalogue:generate`';

const header = (inputs: string) =>
  `// ${HEADER_MARK} from ${inputs}.\n// Do not edit: change the inputs and regenerate. \`pnpm catalogue:check\` rejects a stale copy.\n`;

const data = (value: unknown) => JSON.stringify(value, null, 2);

export const registryUrl = (id: string) => `https://ultima.systems/r/${id}.json`;

function registryProjection(catalogue: Catalogue): string {
  const installable = [
    ...catalogue.sourceBundles,
    ...[...catalogue.react].sort((a, b) => ordinal(a.id, b.id)),
    ...catalogue.artifacts,
    ...[...catalogue.elements].sort((a, b) => ordinal(a.id, b.id)),
  ];
  const items = Object.fromEntries(
    installable.map((entry) => [
      entry.id,
      {
        title: entry.title,
        description: entry.description,
        docs: entry.installDocs,
        ...(entry.kind === 'element' && { registryDependencies: entry.registryDependencies.map(registryUrl) }),
      },
    ]),
  );
  const setupItems = Object.fromEntries(
    catalogue.setup.map(({ id, title, description, dependencies, devDependencies, handSteps, checks }) => [
      id,
      { title, description, dependencies, devDependencies, handSteps, checks },
    ]),
  );
  return `${header('registry/metadata/ and the component sources')}
import type { HandStep } from '../packages/cli/src/hand-steps.ts';

/** \`docs\` is printed by the shadcn CLI after an install. */
export type RegistryItemDescription = {
  title: string;
  description: string;
  docs: string;
  /** Element items only: a vendored bundle has no imports to derive from, so its descriptor declares them. */
  registryDependencies?: string[];
};

/**
 * A setup item's \`docs\` and the install page's list are generated from \`handSteps\`, and
 * \`doctor\` checks every step and every entry in \`checks\`.
 */
export type SetupItemDescription = {
  title: string;
  description: string;
  dependencies: string[];
  devDependencies: string[];
  handSteps: HandStep[];
  checks: HandStep[];
};

export const items: Record<string, RegistryItemDescription> = ${data(items)};

export const setupItems = ${data(setupItems)} satisfies Record<string, SetupItemDescription>;
`;
}

function catalogueProjection(catalogue: Catalogue): string {
  const releases = catalogue.releases.map((release) => release.id);
  const rank = (group: string) => catalogue.groups.findIndex((entry) => entry.id === group);
  const components = [...catalogue.react]
    .sort((a, b) => rank(a.group) - rank(b.group) || ordinal(a.id, b.id))
    .map((entry) => ({
      name: entry.title,
      item: entry.id,
      number: entry.number,
      group: entry.group,
      description: entry.docsDescription ?? entry.description,
      release: entry.release,
    }));
  return `${header('registry/metadata/groups.ts, registry/metadata/releases.ts and registry/metadata/react/')}
import type { ComponentEntry } from '../components';

/** In display order. */
export const GROUPS = ${data(catalogue.groups)} as const;

export const RELEASES = ${data(releases)} as const;

/** By group, then alphabetically. \`number\` is the catalogue number, derived from id order. */
export const components: ComponentEntry[] = ${data(components)};
`;
}

function pagesProjection(catalogue: Catalogue): string {
  const pages = [...catalogue.react].sort((a, b) => ordinal(a.id, b.id));
  const imports = pages.map((entry) => `import ${entry.primaryExport}Content from '../content/components/${entry.id}.mdx';`);
  const map = pages.map((entry) => `  ${JSON.stringify(entry.id)}: ${entry.primaryExport}Content,`);
  return `${header('registry/metadata/react/')}
import type { MDXComponents } from 'mdx/types';
import type { ComponentType } from 'react';

${imports.join('\n')}

export const componentPages: Record<string, ComponentType<{ components?: MDXComponents }>> = {
${map.join('\n')}
};
`;
}

function elementsProjection(catalogue: Catalogue): string {
  const elements = catalogue.elements.map((entry) => ({
    item: entry.reactItem,
    tag: entry.id,
    tags: entry.tags,
    attributes: entry.attributes.map(({ names, on, values }) => ({ name: names.join(', '), on, values })),
    example: entry.example,
  }));
  return `${header('registry/metadata/element/ and the tag and value tables in packages/elements/src/')}
import type { ElementEntry } from '../elements';

export const elements: readonly ElementEntry[] = ${data(elements)};
`;
}

function barrelProjection(catalogue: Catalogue): string {
  const byItem = new Map<string, string[]>();
  for (const entry of catalogue.exports.values()) {
    byItem.set(entry.item, [...(byItem.get(entry.item) ?? []), entry.kind === 'type' ? `type ${entry.name}` : entry.name]);
  }
  const statements = [...byItem.keys()]
    .sort(ordinal)
    .map((item) => `export {\n${(byItem.get(item) as string[]).map((name) => `  ${name},\n`).join('')}} from './${item}';`);
  return `${header("each component file's explicit exports under packages/ui/src/")}
${statements.join('\n')}
`;
}

function browserProjection(plan: OptimizerPlan): string {
  return `${header('the browser-test import closures and scripts/catalogue/optimizer-policy.ts')}
// \`pnpm catalogue:generate provenance\` names the file that brings in each entry.

/** packages/ui/vitest.config.ts: prebundled up front, since discovering one mid-run reloads the page. */
export const uiOptimizerInclude = ${data(plan.include.ui)};

/** apps/docs/vitest.config.ts: prebundled up front, since discovering one mid-run reloads the page. */
export const docsOptimizerInclude = ${data(plan.include.docs)};
`;
}

/**
 * Every owned output's expected bytes, computed from the inputs alone: a committed projection is
 * never read, and imports that traverse one resolve against the planned text instead.
 */
export function planOutputs(
  files: Files,
  policy: OptimizerPolicy,
): { outputs: Map<string, string>; optimizer: OptimizerPlan; diagnostics: Diagnostic[] } {
  const { catalogue, diagnostics } = loadCatalogue(files);
  const outputs = new Map<string, string>([
    [OUTPUTS.registry, registryProjection(catalogue)],
    [OUTPUTS.catalogue, catalogueProjection(catalogue)],
    [OUTPUTS.pages, pagesProjection(catalogue)],
    [OUTPUTS.elements, elementsProjection(catalogue)],
    [OUTPUTS.barrel, barrelProjection(catalogue)],
  ]);
  const barrel = new Map([...catalogue.exports.values()].map((entry) => [entry.name, `packages/ui/src/${entry.item}.tsx`]));
  const browser = browserDependencies(files, outputs, barrel, policy);
  outputs.set(OUTPUTS.browser, browserProjection(browser.plan));
  return { outputs, optimizer: browser.plan, diagnostics: [...diagnostics, ...browser.diagnostics] };
}
