import { type OptimizerPlan, type OptimizerPolicy, browserDependencies, ordinal } from './browser.ts';
import type { Files } from './files.ts';
import { BARREL, type Catalogue, type Diagnostic, type ReactEntry, loadCatalogue } from './model.ts';
import type { Export } from './source.ts';

export const ANATOMY = 'apps/docs/src/generated/anatomy';

export const anatomyModule = (id: string) => `${ANATOMY}/${id}.tsx`;

/** Every fixed path the generator owns. It writes these and one `anatomyModule` per React item, and nothing else. */
export const OUTPUTS = {
  registry: 'registry/items.config.ts',
  catalogue: 'apps/docs/src/generated/catalogue.ts',
  pages: 'apps/docs/src/generated/component-pages.ts',
  elements: 'apps/docs/src/generated/elements.ts',
  blocks: 'apps/docs/src/generated/blocks.ts',
  anatomy: 'apps/docs/src/generated/anatomy-tabs.ts',
  anatomyBarrel: `${ANATOMY}/index.ts`,
  barrel: BARREL,
  browser: 'scripts/generated/browser-dependencies.ts',
} as const;

/** Directories holding only generated files, so anything else there is stale. */
export const GENERATED_DIRECTORIES = ['apps/docs/src/generated', ANATOMY, 'scripts/generated'];

export const HEADER_MARK = 'Generated by `pnpm catalogue:generate`';

const header = (inputs: string) =>
  `// ${HEADER_MARK} from ${inputs}.\n// Do not edit: change the inputs and regenerate. \`pnpm catalogue:check\` rejects a stale copy.\n`;

const data = (value: unknown) => JSON.stringify(value, null, 2);

export const registryUrl = (id: string) => `https://ultima.systems/r/${id}.json`;

function registryProjection(catalogue: Catalogue): string {
  const installable = [
    ...catalogue.sourceBundles,
    ...[...catalogue.react].sort((a, b) => ordinal(a.id, b.id)),
    ...catalogue.artifacts,
    ...[...catalogue.elements].sort((a, b) => ordinal(a.id, b.id)),
    ...[...catalogue.blocks].sort((a, b) => ordinal(a.id, b.id)),
  ];
  const items = Object.fromEntries(
    installable.map((entry) => [
      entry.id,
      {
        title: entry.title,
        description: entry.description,
        docs: entry.installDocs,
        ...(entry.kind === 'element' && { registryDependencies: entry.registryDependencies.map(registryUrl) }),
      },
    ]),
  );
  const setupItems = Object.fromEntries(
    catalogue.setup.map(({ id, title, description, dependencies, devDependencies, handSteps, checks }) => [
      id,
      { title, description, dependencies, devDependencies, handSteps, checks },
    ]),
  );
  return `${header('registry/metadata/ and the component sources')}
import type { HandStep } from '../packages/cli/src/hand-steps.ts';

/** \`docs\` is printed by the shadcn CLI after an install. */
export type RegistryItemDescription = {
  title: string;
  description: string;
  docs: string;
  /** Element items only: a vendored bundle has no imports to derive from, so its descriptor declares them. */
  registryDependencies?: string[];
};

/**
 * A setup item's \`docs\` and the install page's list are generated from \`handSteps\`, and
 * \`doctor\` checks every step and every entry in \`checks\`.
 */
export type SetupItemDescription = {
  title: string;
  description: string;
  dependencies: string[];
  devDependencies: string[];
  handSteps: HandStep[];
  checks: HandStep[];
};

export const items: Record<string, RegistryItemDescription> = ${data(items)};

export const setupItems = ${data(setupItems)} satisfies Record<string, SetupItemDescription>;
`;
}

const NON_COMPONENT_MODULES = new Set(['use-render', 'merge-props', 'direction-provider', 'csp-provider', 'react', 'core', 'types']);

function primitiveOf(entry: ReactEntry): { library: 'base-ui' | 'zag'; module: string } | null {
  const modules = entry.imports.flatMap(({ specifier, typeOnly }) => {
    const match = /^@(base-ui)\/react\/([a-z-]+)$|^@zag-js\/([a-z-]+)$/.exec(specifier);
    if (typeOnly || !match) return [];
    const module = (match[2] ?? match[3]) as string;
    return NON_COMPONENT_MODULES.has(module) ? [] : [{ library: match[1] ? ('base-ui' as const) : ('zag' as const), module }];
  });
  return modules.find(({ module }) => module === entry.id) ?? modules[0] ?? null;
}

function catalogueProjection(catalogue: Catalogue): string {
  const releases = catalogue.releases.map((release) => release.id);
  const rank = (group: string) => catalogue.groups.findIndex((entry) => entry.id === group);
  const components = [...catalogue.react]
    .sort((a, b) => rank(a.group) - rank(b.group) || ordinal(a.id, b.id))
    .map((entry) => ({
      name: entry.title,
      item: entry.id,
      number: entry.number,
      group: entry.group,
      description: entry.docsDescription ?? entry.description,
      release: entry.release,
      primitive: primitiveOf(entry),
    }));
  return `${header('registry/metadata/groups.ts, registry/metadata/releases.ts and registry/metadata/react/')}
import type { ComponentEntry } from '../components';

/** In display order. */
export const GROUPS = ${data(catalogue.groups)} as const;

export const RELEASES = ${data(releases)} as const;

/** By group, then alphabetically. \`number\` is the catalogue number, derived from id order. */
export const components: ComponentEntry[] = ${data(components)};
`;
}

function pagesProjection(catalogue: Catalogue): string {
  const pages = [...catalogue.react].sort((a, b) => ordinal(a.id, b.id));
  const imports = pages.map((entry) => `import ${entry.primaryExport}Content from '../content/components/${entry.id}.mdx';`);
  const map = pages.map((entry) => `  ${JSON.stringify(entry.id)}: ${entry.primaryExport}Content,`);
  return `${header('registry/metadata/react/')}
import type { MDXComponents } from 'mdx/types';
import type { ComponentType } from 'react';

${imports.join('\n')}

export const componentPages: Record<string, ComponentType<{ components?: MDXComponents }>> = {
${map.join('\n')}
};
`;
}

function elementsProjection(catalogue: Catalogue): string {
  const elements = catalogue.elements.map((entry) => ({
    item: entry.reactItem,
    tag: entry.id,
    tags: entry.tags,
    attributes: entry.attributes.map(({ names, on, values }) => ({ name: names.join(', '), on, values })),
    example: entry.example,
  }));
  return `${header('registry/metadata/element/ and the tag and value tables in packages/elements/src/')}
import type { ElementEntry } from '../elements';

export const elements: readonly ElementEntry[] = ${data(elements)};
`;
}

function blocksProjection(catalogue: Catalogue): string {
  const imports = catalogue.blocks.map((entry) => `import { ${entry.primaryExport} } from '@ultima/blocks/${entry.id}/${entry.id}';`);
  const entries = catalogue.blocks.map((entry) => {
    const fields = data({
      id: entry.id,
      title: entry.title,
      description: entry.description,
      number: entry.number,
      install: `npx shadcn add @ultima/${entry.id}`,
      installDocs: entry.installDocs,
      files: entry.files,
      builtFrom: entry.builtFrom,
    });
    return `  ${fields.slice(0, -2).replaceAll('\n', '\n  ')},\n    "preview": ${entry.primaryExport}\n  }`;
  });
  return `${header('registry/metadata/block/ and packages/blocks/src/')}
import type { ComponentType } from 'react';
${imports.length > 0 ? `\n${imports.join('\n')}\n` : ''}
/** A component the block imports, or a recipe it follows, numbered among its own kind. */
export type BuiltFrom = { id: string; title: string; number: string; kind: 'component' | 'recipe' };

export type BlockEntry = {
  id: string;
  title: string;
  description: string;
  /** The catalogue number, derived from id order among blocks. */
  number: string;
  install: string;
  /** How to render it and what to replace, from the descriptor. */
  installDocs: string;
  /** The files installed under \`components/<id>/\`, the entry first. */
  files: readonly string[];
  /** The components it imports in number order, then the recipes it follows. */
  builtFrom: readonly BuiltFrom[];
  /** The root component, which takes no props. */
  preview: ComponentType;
};

/** In number order. */
export const blocks: readonly BlockEntry[] = [${entries.length > 0 ? `\n${entries.join(',\n')},\n` : ''}];
`;
}

const exportName = (item: Export) => (item.kind === 'type' ? `type ${item.name}` : item.name);

function anatomyProjection(entry: ReactEntry): string {
  const source = `@ultima/ui/${entry.id}`;
  const rest = entry.exports.filter((item) => item.name !== entry.primaryExport);
  const reexport = (items: Export[]) => `export {\n${items.map((item) => `  ${exportName(item)},\n`).join('')}} from '${source}';\n`;
  // An arrow, a `memo` or a part object with nothing to mark passes through untouched.
  if (entry.parts.length === 0) return `${header(`registry/metadata/react/${entry.id}.ts and ${entry.source}`)}\n${reexport(entry.exports)}`;
  const marked = (part: string, from: string) => `mark(${from}, '${entry.id}', '${part}')`;
  const single = entry.parts.length === 1 && entry.parts[0] === entry.primaryExport;
  const value = single
    ? marked(entry.primaryExport, 'Source')
    : `{\n  ...Source,\n${entry.parts.map((part) => `  ${part}: ${marked(part, `Source.${part}`)},\n`).join('')}}`;
  return `${header(`registry/metadata/react/${entry.id}.ts and ${entry.source}`)}
import { ${entry.primaryExport} as Source } from '${source}';

import { mark } from '../../anatomy-mark';
${rest.length > 0 ? `\n${reexport(rest)}` : ''}
export const ${entry.primaryExport} = ${value};
`;
}

function anatomyBarrelProjection(catalogue: Catalogue): string {
  const statements = [...catalogue.react]
    .sort((a, b) => ordinal(a.id, b.id))
    .map((entry) => `export {\n${entry.exports.map((item) => `  ${exportName(item)},\n`).join('')}} from './${entry.id}';`);
  return `${header('registry/metadata/react/ and the component sources')}
${statements.join('\n')}
`;
}

function anatomyTabsProjection(catalogue: Catalogue): string {
  const entries = [...catalogue.react].sort((a, b) => ordinal(a.id, b.id));
  const demoName = (entry: ReactEntry) => `${entry.primaryExport}Anatomy`;
  const imports = entries
    .filter((entry) => entry.anatomyDemo)
    .map((entry) => `import ${demoName(entry)} from '../demos/${entry.id}/anatomy';`);
  const map = entries.map(
    (entry) =>
      `  '${entry.id}': { parts: [${entry.parts.map((part) => `'${part}'`).join(', ')}]${entry.anatomyDemo ? `, demo: ${demoName(entry)}` : ''} },`,
  );
  return `${header('registry/metadata/react/, the component sources and apps/docs/src/demos/*/anatomy.tsx')}
import type { ComponentType } from 'react';
${imports.length > 0 ? `\n${imports.join('\n')}\n` : ''}
/** Each React item's parts that render an element, and the open overlay its Anatomy tab renders when it has one. */
export const anatomyTabs: Record<string, { parts: readonly string[]; demo?: ComponentType }> = {
${map.join('\n')}
};
`;
}

function barrelProjection(catalogue: Catalogue): string {
  const byItem = new Map<string, string[]>();
  for (const entry of catalogue.exports.values()) {
    byItem.set(entry.item, [...(byItem.get(entry.item) ?? []), entry.kind === 'type' ? `type ${entry.name}` : entry.name]);
  }
  const statements = [...byItem.keys()]
    .sort(ordinal)
    .map((item) => `export {\n${(byItem.get(item) as string[]).map((name) => `  ${name},\n`).join('')}} from './${item}';`);
  return `${header("each component file's explicit exports under packages/ui/src/")}
${statements.join('\n')}
`;
}

function browserProjection(plan: OptimizerPlan): string {
  return `${header('the browser-test import closures and scripts/catalogue/optimizer-policy.ts')}
// \`pnpm catalogue:generate provenance\` names the file that brings in each entry.

/** packages/ui/vitest.config.ts: prebundled up front, since discovering one mid-run reloads the page. */
export const uiOptimizerInclude = ${data(plan.include.ui)};

/** apps/docs/vitest.config.ts: prebundled up front, since discovering one mid-run reloads the page. */
export const docsOptimizerInclude = ${data(plan.include.docs)};

/** packages/blocks/vitest.config.ts: prebundled up front, since discovering one mid-run reloads the page. */
export const blocksOptimizerInclude = ${data(plan.include.blocks)};
`;
}

/**
 * Every owned output's expected bytes, computed from the inputs alone: a committed projection is
 * never read, and imports that traverse one resolve against the planned text instead.
 */
export function planOutputs(
  files: Files,
  policy: OptimizerPolicy,
): { outputs: Map<string, string>; optimizer: OptimizerPlan; diagnostics: Diagnostic[] } {
  const { catalogue, diagnostics } = loadCatalogue(files);
  const outputs = new Map<string, string>([
    [OUTPUTS.registry, registryProjection(catalogue)],
    [OUTPUTS.catalogue, catalogueProjection(catalogue)],
    [OUTPUTS.pages, pagesProjection(catalogue)],
    [OUTPUTS.elements, elementsProjection(catalogue)],
    [OUTPUTS.blocks, blocksProjection(catalogue)],
    [OUTPUTS.anatomy, anatomyTabsProjection(catalogue)],
    [OUTPUTS.anatomyBarrel, anatomyBarrelProjection(catalogue)],
    ...[...catalogue.react]
      .sort((a, b) => ordinal(a.id, b.id))
      .map((entry): [string, string] => [anatomyModule(entry.id), anatomyProjection(entry)]),
    [OUTPUTS.barrel, barrelProjection(catalogue)],
  ]);
  const barrel = new Map([...catalogue.exports.values()].map((entry) => [entry.name, `packages/ui/src/${entry.item}.tsx`]));
  const browser = browserDependencies(files, outputs, barrel, policy);
  outputs.set(OUTPUTS.browser, browserProjection(browser.plan));
  return { outputs, optimizer: browser.plan, diagnostics: [...diagnostics, ...browser.diagnostics] };
}
