/**
 * StyleX cannot read the palette constants from another file, so the values
 * here are the same hex as tokens.stylex.ts, copied from scripts/palette.json.
 * A StyleX theme can only override tokens, and `color-scheme` is a property,
 * so it rides beside the theme: apply `stylex.props(darkTheme, colorScheme.dark)`.
 */
import * as stylex from '@stylexjs/stylex';
import { color } from './tokens.stylex';

export const colorScheme = stylex.create({
  system: { colorScheme: { default: 'dark', '@media (prefers-color-scheme: light)': 'light' } },
  dark: { colorScheme: 'dark' },
  light: { colorScheme: 'light' },
});

export const darkTheme = stylex.createTheme(color, {
  '--ult-color-surface': '#0b0d17',
  '--ult-color-surface-raised': '#111324',
  '--ult-color-surface-sunken': '#181c33',
  '--ult-color-surface-hover': '#212540',
  '--ult-color-surface-overlay': '#11132499',
  '--ult-color-text': '#e3e7f7',
  '--ult-color-text-muted': '#afb6d4',
  '--ult-color-text-subtle': '#8990b4',
  '--ult-color-text-inverse': '#0b0d17',
  '--ult-color-border': '#353a5a',
  '--ult-color-border-strong': '#5a6183',
  '--ult-color-border-focus': '#8394ff',
  '--ult-color-action': '#44d4e1',
  '--ult-color-action-hover': '#59e4f2',
  '--ult-color-action-active': '#79f0fc',
  '--ult-color-action-contrast': '#0b0d17',
  '--ult-color-accent': '#8394ff',
  '--ult-color-accent-hover': '#96a7ff',
  '--ult-color-accent-active': '#aab9ff',
  '--ult-color-accent-subtle': '#161a3d',
  '--ult-color-accent-border': '#3a4295',
  '--ult-color-accent-text': '#c3ceff',
  '--ult-color-accent-contrast': '#0b0d17',
  '--ult-color-highlight': '#44d4e1',
  '--ult-color-highlight-hover': '#59e4f2',
  '--ult-color-highlight-active': '#79f0fc',
  '--ult-color-highlight-subtle': '#002327',
  '--ult-color-highlight-border': '#00585f',
  '--ult-color-highlight-text': '#8ff5ff',
  '--ult-color-highlight-contrast': '#0b0d17',
  '--ult-color-success': '#56cb98',
  '--ult-color-success-hover': '#67dba7',
  '--ult-color-success-active': '#81e6b6',
  '--ult-color-success-subtle': '#002516',
  '--ult-color-success-border': '#005c3d',
  '--ult-color-success-text': '#9becc4',
  '--ult-color-success-contrast': '#0b0d17',
  '--ult-color-warning': '#eab352',
  '--ult-color-warning-hover': '#f8c060',
  '--ult-color-warning-active': '#ffcf80',
  '--ult-color-warning-subtle': '#2a1b00',
  '--ult-color-warning-border': '#664600',
  '--ult-color-warning-text': '#ffd898',
  '--ult-color-warning-contrast': '#0b0d17',
  '--ult-color-danger': '#df6769',
  '--ult-color-danger-hover': '#f07778',
  '--ult-color-danger-active': '#fb8c8c',
  '--ult-color-danger-subtle': '#351011',
  '--ult-color-danger-border': '#822b2f',
  '--ult-color-danger-text': '#ffaaa8',
  '--ult-color-danger-contrast': '#0b0d17',
});

export const lightTheme = stylex.createTheme(color, {
  '--ult-color-surface': '#fdfdff',
  '--ult-color-surface-raised': '#f7f9ff',
  '--ult-color-surface-sunken': '#eff1fa',
  '--ult-color-surface-hover': '#e7e9f3',
  '--ult-color-surface-overlay': '#f7f9ffcc',
  '--ult-color-text': '#181a24',
  '--ult-color-text-muted': '#4f525e',
  '--ult-color-text-subtle': '#60636f',
  '--ult-color-text-inverse': '#fdfdff',
  '--ult-color-border': '#d0d3e2',
  '--ult-color-border-strong': '#888b99',
  '--ult-color-border-focus': '#565fde',
  '--ult-color-action': '#00818b',
  '--ult-color-action-hover': '#00717a',
  '--ult-color-action-active': '#00646c',
  '--ult-color-action-contrast': '#fdfdff',
  '--ult-color-accent': '#565fde',
  '--ult-color-accent-hover': '#494fcc',
  '--ult-color-accent-active': '#4042bf',
  '--ult-color-accent-subtle': '#eef1ff',
  '--ult-color-accent-border': '#b3c0ff',
  '--ult-color-accent-text': '#343997',
  '--ult-color-accent-contrast': '#fdfdff',
  '--ult-color-highlight': '#00818b',
  '--ult-color-highlight-hover': '#00717a',
  '--ult-color-highlight-active': '#00646c',
  '--ult-color-highlight-subtle': '#dcf8fb',
  '--ult-color-highlight-border': '#85d3db',
  '--ult-color-highlight-text': '#00585f',
  '--ult-color-highlight-contrast': '#fdfdff',
  '--ult-color-success': '#008359',
  '--ult-color-success-hover': '#00734d',
  '--ult-color-success-active': '#006644',
  '--ult-color-success-subtle': '#defaeb',
  '--ult-color-success-border': '#8dd7b2',
  '--ult-color-success-text': '#005c3d',
  '--ult-color-success-contrast': '#fdfdff',
  '--ult-color-warning': '#e7ac3e',
  '--ult-color-warning-hover': '#d39923',
  '--ult-color-warning-active': '#bf8600',
  '--ult-color-warning-subtle': '#fff0d8',
  '--ult-color-warning-border': '#e4be7f',
  '--ult-color-warning-text': '#714e00',
  '--ult-color-warning-contrast': '#181a24',
  '--ult-color-danger': '#cb454c',
  '--ult-color-danger-hover': '#ba343e',
  '--ult-color-danger-active': '#a82131',
  '--ult-color-danger-subtle': '#ffedec',
  '--ult-color-danger-border': '#ffaaa8',
  '--ult-color-danger-text': '#88222b',
  '--ult-color-danger-contrast': '#fdfdff',
});
