/**
 * The semantic groups are `defineVars` keyed by their full custom property
 * name so StyleX emits `--ult-<group>-<name>` verbatim (ADR 0004).
 *
 * StyleX rule: a `.stylex.ts` file may export nothing but `defineVars` and
 * `defineConsts` calls.
 */
import * as stylex from '@stylexjs/stylex';

const LIGHT = '@media (prefers-color-scheme: light)';
const REDUCED_MOTION = '@media (prefers-reduced-motion: reduce)';

export const mithril = stylex.defineConsts({
  dark1: '#0e0e0e',
  dark2: '#151515',
  dark3: '#1e1e1e',
  dark4: '#282828',
  dark5: '#313131',
  dark6: '#3d3d3d',
  dark7: '#4d4d4d',
  dark8: '#636363',
  dark9: '#808080',
  dark10: '#929292',
  dark11: '#b7b7b7',
  dark12: '#e8e8e8',
  light1: '#fdfdfd',
  light2: '#f9f9f9',
  light3: '#f2f2f2',
  light4: '#e9e9e9',
  light5: '#dfdfdf',
  light6: '#d4d4d4',
  light7: '#b7b7b7',
  light8: '#8c8c8c',
  light9: '#747474',
  light10: '#636363',
  light11: '#525252',
  light12: '#1b1b1b',
});

export const arcane = stylex.defineConsts({
  dark1: '#0e0e0e',
  dark2: '#151515',
  dark3: '#1e1e1e',
  dark4: '#282828',
  dark5: '#313131',
  dark6: '#3d3d3d',
  dark7: '#4d4d4d',
  dark8: '#636363',
  dark9: '#9e9e9e',
  dark10: '#aeaeae',
  dark11: '#bebebe',
  dark12: '#d1d1d1',
  light1: '#fdfdfd',
  light2: '#f9f9f9',
  light3: '#f2f2f2',
  light4: '#e9e9e9',
  light5: '#dfdfdf',
  light6: '#d4d4d4',
  light7: '#c4c4c4',
  light8: '#ababab',
  light9: '#717171',
  light10: '#636363',
  light11: '#585858',
  light12: '#484848',
});

export const mana = stylex.defineConsts({
  dark1: '#0e0e0e',
  dark2: '#151515',
  dark3: '#1e1e1e',
  dark4: '#282828',
  dark5: '#313131',
  dark6: '#3d3d3d',
  dark7: '#4d4d4d',
  dark8: '#636363',
  dark9: '#bebebe',
  dark10: '#cecece',
  dark11: '#dbdbdb',
  dark12: '#e2e2e2',
  light1: '#fdfdfd',
  light2: '#f9f9f9',
  light3: '#f2f2f2',
  light4: '#e9e9e9',
  light5: '#dfdfdf',
  light6: '#d4d4d4',
  light7: '#c4c4c4',
  light8: '#ababab',
  light9: '#717171',
  light10: '#636363',
  light11: '#585858',
  light12: '#4d4d4d',
});

export const verdant = stylex.defineConsts({
  dark1: '#06100b',
  dark2: '#061910',
  dark3: '#002516',
  dark4: '#00311e',
  dark5: '#003c26',
  dark6: '#004a30',
  dark7: '#005c3d',
  dark8: '#00764f',
  dark9: '#56cb98',
  dark10: '#67dba7',
  dark11: '#81e6b6',
  dark12: '#9becc4',
  light1: '#fafffc',
  light2: '#f0fdf6',
  light3: '#defaeb',
  light4: '#cef4e0',
  light5: '#bbedd3',
  light6: '#a7e5c5',
  light7: '#8dd7b2',
  light8: '#62c195',
  light9: '#008359',
  light10: '#00734d',
  light11: '#006644',
  light12: '#005c3d',
});

export const ember = stylex.defineConsts({
  dark1: '#120d05',
  dark2: '#1d1304',
  dark3: '#2a1b00',
  dark4: '#372400',
  dark5: '#432d00',
  dark6: '#523700',
  dark7: '#664600',
  dark8: '#835b00',
  dark9: '#eab352',
  dark10: '#f8c060',
  dark11: '#ffcf80',
  dark12: '#ffd898',
  light1: '#fffdfa',
  light2: '#fff8ee',
  light3: '#fff0d8',
  light4: '#fce6c5',
  light5: '#f7dcb1',
  light6: '#f0cf9b',
  light7: '#e4be7f',
  light8: '#d1a252',
  light9: '#e7ac3e',
  light10: '#d39923',
  light11: '#bf8600',
  light12: '#714e00',
});

export const ruin = stylex.defineConsts({
  dark1: '#160a09',
  dark2: '#230d0d',
  dark3: '#351011',
  dark4: '#461517',
  dark5: '#561a1d',
  dark6: '#6a2024',
  dark7: '#822b2f',
  dark8: '#a23c40',
  dark9: '#df6769',
  dark10: '#f07778',
  dark11: '#fb8c8c',
  dark12: '#ffaaa8',
  light1: '#fffdfd',
  light2: '#fff7f6',
  light3: '#ffedec',
  light4: '#ffe1e0',
  light5: '#ffd4d2',
  light6: '#ffc3c1',
  light7: '#ffaaa8',
  light8: '#f58585',
  light9: '#cb454c',
  light10: '#ba343e',
  light11: '#a82131',
  light12: '#88222b',
});

// Generated by packages/tokens/scripts/base-theme.ts from stockDraft(). Do not edit.
export const color = stylex.defineVars({
  '--ult-color-surface': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-surface-raised': { default: mithril.dark2, [LIGHT]: mithril.light2 },
  '--ult-color-surface-sunken': { default: mithril.dark3, [LIGHT]: mithril.light3 },
  '--ult-color-surface-hover': { default: mithril.dark4, [LIGHT]: mithril.light4 },
  '--ult-color-surface-active': { default: mithril.dark5, [LIGHT]: mithril.light5 },
  '--ult-color-text': { default: mithril.dark12, [LIGHT]: mithril.light12 },
  '--ult-color-text-muted': { default: mithril.dark11, [LIGHT]: mithril.light11 },
  '--ult-color-text-subtle': { default: mithril.dark10, [LIGHT]: mithril.light10 },
  '--ult-color-text-inverse': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-border': { default: mithril.dark6, [LIGHT]: mithril.light6 },
  '--ult-color-border-strong': { default: mithril.dark8, [LIGHT]: mithril.light8 },
  '--ult-color-border-focus': { default: arcane.dark9, [LIGHT]: arcane.light9 },
  '--ult-color-action': { default: mana.dark9, [LIGHT]: mana.light9 },
  '--ult-color-action-hover': { default: mana.dark10, [LIGHT]: mana.light10 },
  '--ult-color-action-active': { default: mana.dark11, [LIGHT]: mana.light11 },
  '--ult-color-accent': { default: mithril.dark12, [LIGHT]: mithril.light12 },
  '--ult-color-accent-hover': { default: '#d4d4d4', [LIGHT]: '#2e2e2e' },
  '--ult-color-accent-active': { default: '#c4c4c4', [LIGHT]: '#3d3d3d' },
  '--ult-color-accent-subtle': { default: mithril.dark3, [LIGHT]: mithril.light3 },
  '--ult-color-accent-border': { default: mithril.dark7, [LIGHT]: mithril.light7 },
  '--ult-color-accent-text': { default: mithril.dark12, [LIGHT]: mithril.light12 },
  '--ult-color-highlight': { default: mana.dark9, [LIGHT]: mana.light9 },
  '--ult-color-highlight-hover': { default: mana.dark10, [LIGHT]: mana.light10 },
  '--ult-color-highlight-active': { default: mana.dark11, [LIGHT]: mana.light11 },
  '--ult-color-highlight-subtle': { default: mana.dark3, [LIGHT]: mana.light3 },
  '--ult-color-highlight-border': { default: mana.dark7, [LIGHT]: mana.light7 },
  '--ult-color-highlight-text': { default: mana.dark12, [LIGHT]: mana.light12 },
  '--ult-color-success': { default: verdant.dark9, [LIGHT]: verdant.light9 },
  '--ult-color-success-hover': { default: verdant.dark10, [LIGHT]: verdant.light10 },
  '--ult-color-success-active': { default: verdant.dark11, [LIGHT]: verdant.light11 },
  '--ult-color-success-subtle': { default: verdant.dark3, [LIGHT]: verdant.light3 },
  '--ult-color-success-border': { default: verdant.dark7, [LIGHT]: verdant.light7 },
  '--ult-color-success-text': { default: verdant.dark12, [LIGHT]: verdant.light12 },
  '--ult-color-warning': { default: ember.dark9, [LIGHT]: ember.light9 },
  '--ult-color-warning-hover': { default: ember.dark10, [LIGHT]: ember.light10 },
  '--ult-color-warning-active': { default: ember.dark11, [LIGHT]: ember.light11 },
  '--ult-color-warning-subtle': { default: ember.dark3, [LIGHT]: ember.light3 },
  '--ult-color-warning-border': { default: ember.dark7, [LIGHT]: ember.light7 },
  '--ult-color-warning-text': { default: ember.dark12, [LIGHT]: ember.light12 },
  '--ult-color-danger': { default: ruin.dark9, [LIGHT]: ruin.light9 },
  '--ult-color-danger-hover': { default: ruin.dark10, [LIGHT]: ruin.light10 },
  '--ult-color-danger-active': { default: ruin.dark11, [LIGHT]: ruin.light11 },
  '--ult-color-danger-subtle': { default: ruin.dark3, [LIGHT]: ruin.light3 },
  '--ult-color-danger-border': { default: ruin.dark7, [LIGHT]: ruin.light7 },
  '--ult-color-danger-text': { default: ruin.dark12, [LIGHT]: ruin.light12 },
  '--ult-color-accent-contrast': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-highlight-contrast': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-success-contrast': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-warning-contrast': { default: mithril.dark1, [LIGHT]: mithril.light12 },
  '--ult-color-danger-contrast': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-action-contrast': { default: mithril.dark1, [LIGHT]: mithril.light1 },
  '--ult-color-surface-overlay': { default: `${mithril.dark2}b3`, [LIGHT]: `${mithril.light2}cc` },
});

export const space = stylex.defineVars({
  '--ult-space-1': '0.125rem',
  '--ult-space-2': '0.25rem',
  '--ult-space-3': '0.375rem',
  '--ult-space-4': '0.5rem',
  '--ult-space-5': '0.75rem',
  '--ult-space-6': '1rem',
  '--ult-space-7': '1.25rem',
  '--ult-space-8': '1.5rem',
  '--ult-space-9': '2rem',
  '--ult-space-10': '2.5rem',
  '--ult-space-11': '3rem',
  '--ult-space-12': '4rem',
});

export const text = stylex.defineVars({
  '--ult-text-1': '0.6875rem',
  '--ult-text-2': '0.75rem',
  '--ult-text-3': '0.8125rem',
  '--ult-text-4': '0.875rem',
  '--ult-text-5': '1rem',
  '--ult-text-6': '1.125rem',
  '--ult-text-7': '1.25rem',
  '--ult-text-8': '1.5rem',
  '--ult-text-9': '1.875rem',
  '--ult-text-10': '2.25rem',
  '--ult-text-11': '3rem',
  '--ult-text-12': '3.25rem',
});

export const font = stylex.defineVars({
  '--ult-font-sans':
    "'Figtree', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
  '--ult-font-mono': "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  '--ult-font-weight-regular': 400,
  '--ult-font-weight-medium': 500,
  '--ult-font-weight-semibold': 600,
  '--ult-font-leading-none': 1,
  '--ult-font-leading-tight': 1.2,
  '--ult-font-leading-snug': 1.35,
  '--ult-font-leading-normal': 1.55,
  '--ult-font-leading-relaxed': 1.75,
  '--ult-font-tracking-tightest': '-0.04em',
  '--ult-font-tracking-tighter': '-0.03em',
  '--ult-font-tracking-tight': '-0.02em',
  '--ult-font-tracking-normal': 0,
  '--ult-font-tracking-wide': '0.08em',
  '--ult-font-tracking-wider': '0.14em',
});

// Generated by packages/tokens/scripts/base-theme.ts from stockDraft(). Do not edit.
export const radius = stylex.defineVars({
  '--ult-radius-xs': '1px',
  '--ult-radius-sm': '2px',
  '--ult-radius-md': '4px',
  '--ult-radius-lg': '6px',
  '--ult-radius-full': '9999px',
});

export const shadow = stylex.defineVars({
  '--ult-shadow-sm': {
    default: '0 1px 2px rgba(0,0,0,.30), 0 1px 3px rgba(0,0,0,.40)',
    [LIGHT]: '0 1px 2px rgba(0,0,0,.06), 0 1px 3px rgba(0,0,0,.10)',
  },
  '--ult-shadow-md': {
    default: '0 4px 8px rgba(0,0,0,.35), 0 8px 24px rgba(0,0,0,.45)',
    [LIGHT]: '0 4px 8px rgba(0,0,0,.08), 0 8px 24px rgba(0,0,0,.12)',
  },
  '--ult-shadow-lg': {
    default: '0 12px 24px rgba(0,0,0,.40), 0 24px 48px rgba(0,0,0,.50)',
    [LIGHT]: '0 12px 24px rgba(0,0,0,.12), 0 24px 48px rgba(0,0,0,.18)',
  },
});

export const filter = stylex.defineVars({
  '--ult-filter-backdrop': 'blur(4px)',
});

export const motion = stylex.defineVars({
  '--ult-motion-fast': { default: '120ms', [REDUCED_MOTION]: '1ms' },
  '--ult-motion-base': { default: '200ms', [REDUCED_MOTION]: '1ms' },
  '--ult-motion-slow': { default: '300ms', [REDUCED_MOTION]: '1ms' },
  '--ult-motion-loop': { default: '1s', [REDUCED_MOTION]: '0s' },
});

export const easing = stylex.defineConsts({
  standard: 'cubic-bezier(.2, 0, 0, 1)',
  enter: 'cubic-bezier(0, 0, .2, 1)',
  exit: 'cubic-bezier(.4, 0, 1, 1)',
});

export const border = stylex.defineConsts({
  hairline: '1px',
  focus: '2px',
  focusOffset: '2px',
});

export const z = stylex.defineConsts({
  popup: 50,
  toast: 60,
});

export const relativeText = stylex.defineConsts({
  code: '0.875em',
});

export const display = stylex.defineConsts({
  section: '1.625rem',
  headline: 'clamp(2rem, 4vw, 2.75rem)',
  hero: 'clamp(2.5rem, 6vw, 4.75rem)',
});
