/** Imported by relative path so `scripts/site-themes.ts` can run it under plain Node. */
import { presetDraft, resolveDraft, type ResolvedDraft, type ThemeDraft } from '../../../packages/tokens/src/theme/draft.ts';

export const SITE_THEMES_PATH = 'apps/docs/src/site-themes.ts';

export function siteDraft(): ThemeDraft {
  const draft = presetDraft('neutral');
  draft.color.mana = { ...presetDraft({ id: 'ultima', revision: 1 }).color.mana };
  return draft;
}

export function neutralDraft(): ThemeDraft {
  return presetDraft('neutral');
}

const THEMES = [
  { name: 'site', draft: siteDraft },
  { name: 'neutral', draft: neutralDraft },
] as const;

function colorTokens(resolved: ResolvedDraft, mode: 'dark' | 'light'): [string, string][] {
  return Object.entries(resolved[mode]).filter(([token]) => token.startsWith('--ult-color-'));
}

export function renderSiteThemes(): string {
  const lines = [
    '// Generated by apps/docs/scripts/site-themes.ts from site-theme-draft.ts. Do not edit:',
    '// run `pnpm --filter @ultima/docs themes:generate`.',
    "import * as stylex from '@stylexjs/stylex';",
    "import { color } from '@ultima/tokens/tokens.stylex';",
  ];
  for (const { name, draft } of THEMES) {
    const resolved = resolveDraft(draft());
    for (const mode of ['dark', 'light'] as const) {
      const exported = `${name}${mode === 'dark' ? 'Dark' : 'Light'}`;
      lines.push('', `export const ${exported} = stylex.createTheme(color, {`);
      for (const [token, value] of colorTokens(resolved, mode)) lines.push(`  '${token}': '${value}',`);
      lines.push('});');
    }
  }
  return `${lines.join('\n')}\n`;
}
