import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { resolveDraft, stockDraft } from '../src/theme/draft.ts';
import { generateScales, SCALE_NAMES } from '../src/theme/recipe.ts';

const packageDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const banner = '// Generated by packages/tokens/scripts/base-theme.ts from stockDraft(). Do not edit.';

export function baseTokenSources(): Map<string, string> {
  const draft = stockDraft();
  const resolved = resolveDraft(draft);
  const scales = generateScales(draft.color, draft.recipeVersion);
  const valueSource = (name: string, mode: 'dark' | 'light'): string => {
    const value = resolved[mode][name];
    if (typeof value !== 'string') throw new Error(`Missing ${name} in ${mode}.`);
    if (name === '--ult-color-surface-overlay') return `\`\${mithril.${mode}2}${value.slice(-2)}\``;
    const role = name.replace('--ult-color-', '').split('-')[0];
    const scale = name === '--ult-color-border-focus' ? 'arcane'
      : name.endsWith('-contrast') || role === 'accent' ? 'mithril'
      : role === 'action' || role === 'highlight' ? 'mana'
      : role === 'success' ? 'verdant' : role === 'warning' ? 'ember' : role === 'danger' ? 'ruin' : 'mithril';
    const index = scales[scale][mode].indexOf(value);
    return index === -1 ? `'${value}'` : `${scale}.${mode}${index + 1}`;
  };
  const colors = Object.keys(resolved.dark).filter((name) => name.startsWith('--ult-color-'));
  const color = [
    banner,
    'export const color = stylex.defineVars({',
    ...colors.map((name) => `  '${name}': { default: ${valueSource(name, 'dark')}, [LIGHT]: ${valueSource(name, 'light')} },`),
    '});',
  ].join('\n');
  const radius = [
    banner,
    'export const radius = stylex.defineVars({',
    ...Object.entries(resolved.dark).filter(([name]) => name.startsWith('--ult-radius-'))
      .map(([name, value]) => `  '${name}': '${value}',`),
    '});',
  ].join('\n');
  const tokenPath = join(packageDir, 'src/tokens.stylex.ts');
  const source = readFileSync(tokenPath, 'utf8');
  const replaceGroup = (source: string, group: string, replacement: string) => {
    const pattern = new RegExp(`(?:// Generated by packages/tokens/scripts/base-theme\\.ts[^\\n]*\\n)?export const ${group} = stylex\\.defineVars\\(\\{[\\s\\S]*?\\n\\}\\);`);
    if (!pattern.test(source)) throw new Error(`Missing base ${group} token group.`);
    return source.replace(pattern, replacement);
  };
  let tokens = replaceGroup(replaceGroup(source, 'color', color), 'radius', radius);
  for (const name of SCALE_NAMES) {
    const pattern = new RegExp(`export const ${name} = stylex\\.defineConsts\\(\\{[\\s\\S]*?\\n\\}\\);`);
    const lines = [`export const ${name} = stylex.defineConsts({`];
    for (const mode of ['dark', 'light'] as const) {
      scales[name][mode].forEach((value, index) => lines.push(`  ${mode}${index + 1}: '${value}',`));
    }
    lines.push('});');
    if (!pattern.test(tokens)) throw new Error(`Missing ${name} palette constants.`);
    tokens = tokens.replace(pattern, lines.join('\n'));
  }
  const themePath = join(packageDir, 'src/themes.ts');
  const colorScheme = readFileSync(themePath, 'utf8').match(/export const colorScheme = stylex\.create\(\{[\s\S]*?\n\}\);/)?.[0];
  if (!colorScheme) throw new Error('Missing colorScheme styles.');
  const themes = [banner, "import * as stylex from '@stylexjs/stylex';", "import { color } from './tokens.stylex';", '', colorScheme];
  for (const mode of ['dark', 'light'] as const) {
    themes.push('', `export const ${mode}Theme = stylex.createTheme(color, {`);
    for (const name of colors) themes.push(`  '${name}': '${resolved[mode][name]}',`);
    themes.push('});');
  }
  return new Map([[tokenPath, tokens], [themePath, `${themes.join('\n')}\n`]]);
}

export function generateBaseSources(): void {
  for (const [path, source] of baseTokenSources()) {
    if (readFileSync(path, 'utf8') !== source) writeFileSync(path, source);
  }
}
